import type { NearbyDriver } from "../types/ride.types";

const FAKE_DRIVERS_TEMPLATE = [
  {
    id: "fake-driver-1",
    firstName: "Alexander",
    lastName: "Wright",
    imageUrl: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80",
    vehicleType: "Electric",
    vehicleModel: "Tesla Model 3",
    vehicleColor: "Pearl White",
    vehiclePlate: "DX-8492",
    rating: 4.9,
    fare: "14.50",
    timeMinutes: 3,
    seats: 4,
    heading: 45,
    latOffset: 0.0009,
    lngOffset: 0.0007,
  },
  {
    id: "fake-driver-2",
    firstName: "Sarah",
    lastName: "Jenkins",
    imageUrl: "https://images.unsplash.com/photo-1580489944761-15a19d654956?w=150&auto=format&fit=crop&q=80",
    vehicleType: "Sedan",
    vehicleModel: "Toyota Camry",
    vehicleColor: "Silver Metallic",
    vehiclePlate: "CA-1029",
    rating: 4.85,
    fare: "12.80",
    timeMinutes: 5,
    seats: 4,
    heading: 200,
    latOffset: -0.0008,
    lngOffset: 0.0010,
  },
  {
    id: "fake-driver-3",
    firstName: "David",
    lastName: "Miller",
    imageUrl: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80",
    vehicleType: "SUV",
    vehicleModel: "Hyundai Santa Fe",
    vehicleColor: "Midnight Black",
    vehiclePlate: "NY-5521",
    rating: 4.95,
    fare: "21.50",
    timeMinutes: 6,
    seats: 6,
    heading: 320,
    latOffset: 0.0012,
    lngOffset: -0.0009,
  },
  {
    id: "fake-driver-4",
    firstName: "Emily",
    lastName: "Zhang",
    imageUrl: "https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=150&auto=format&fit=crop&q=80",
    vehicleType: "Comfort",
    vehicleModel: "Honda Accord",
    vehicleColor: "Deep Blue",
    vehiclePlate: "TX-9901",
    rating: 4.92,
    fare: "15.00",
    timeMinutes: 4,
    seats: 4,
    heading: 110,
    latOffset: -0.0010,
    lngOffset: -0.0008,
  },
  {
    id: "fake-driver-5",
    firstName: "Marcus",
    lastName: "Vance",
    imageUrl: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&auto=format&fit=crop&q=80",
    vehicleType: "Premier",
    vehicleModel: "Mercedes C-Class",
    vehicleColor: "Selenite Grey",
    vehiclePlate: "FL-3382",
    rating: 4.78,
    fare: "26.00",
    timeMinutes: 8,
    seats: 4,
    heading: 10,
    latOffset: 0.0007,
    lngOffset: -0.0013,
  },
];

export function generateFakeDrivers(
  latitude: number,
  longitude: number,
): NearbyDriver[] {
  return FAKE_DRIVERS_TEMPLATE.map((driver) => ({
    id: driver.id,
    firstName: driver.firstName,
    lastName: driver.lastName,
    imageUrl: driver.imageUrl,
    vehicleType: driver.vehicleType,
    vehicleModel: driver.vehicleModel,
    vehicleColor: driver.vehicleColor,
    carPlate: driver.vehiclePlate,
    rating: driver.rating,
    fare: driver.fare,
    timeMinutes: driver.timeMinutes,
    seats: driver.seats,
    heading: driver.heading,
    latitude: latitude + driver.latOffset,
    longitude: longitude + driver.lngOffset,
  }));
}
